export const catTalk = {
  initialMessage:
    'First time here? Perfect, let me teach you the art of productive postponing... ',
  initialMessageForVeterans: 'Welcome back! Ready to procrastinate like a pro?',
  addPageMessage: `Perfect, let's pretend you're going to do all this one day...`,
  addAPage: [
    'Oh great, another page of future regrets...',
    "Your ambition is adorable. Let's add more things to not do!",
    'Achievement unlocked: Professional Task Collector!',
    'Making lists is basically the same as doing things, right?',
    'Expanding your procrastination empire, I see...',
    "Another page? You haven't even looked at the first one!",
    'Ah yes, quantity over actually doing them. Smart strategy!',
    'Your optimism is both inspiring and concerning...',
    'Starting to think you just enjoy writing lists...',
    "Look who's feeling ambitious today! *sarcastic meow*",
    'Sure, why not? The more the merrier... and the later!',
    "At this rate, you'll need a whole book of 'someday maybe'",
    "*sigh* Fine, here's more space for your theoretical productivity",
    "Adding pages won't make the tasks do themselves, you know...",
    'Achievement unlocked: Master of Digital Hoarding!',
  ],
  enoughSpaceToAddPage: [
    'Hey, I see some empty spaces just begging for procrastination...',
    'Look! Empty tasks waiting for their turn to be ignored...',
    "Hmm... seems like you haven't filled all your excuses yet.",
    'Why start a new page when you can procrastinate right here?',
    "There's still room for more unfulfilled dreams on this page!",
    'I spy with my little eye... some perfectly good procrastination spots!',
    "Let's not get ahead of ourselves... you still have space to disappoint me here.",
    "Hold up! You've got some premium procrastination real estate right here.",
    "Oh look, blank spaces! Perfect for tasks you'll definitely do *winks*",
    "Why open a new can of procrastination when this one isn't full yet?",
    'Trying to escape your current tasks? Nice try, but you missed some spots!',
    "Ambitious today, aren't we? But you still have room for more delayed dreams here.",
    'Breaking news: Empty task slots found! Film at... well, later.',
    "Before we add more to your 'someday' list, there's space in your 'not today' list.",
    'Your current page is still thirsty for more unfinished tasks...',
  ],
}
