import { m } from '@/lib/i18n'

export const getCatTalk = () => ({
  initialMessage: m.cat_initialMessage(),
  initialMessageForVeterans: m.cat_initialMessageForVeterans(),
  addPageMessage: m.cat_addPageMessage(),
  addAPage: [
    m.cat_addAPage_0(),
    m.cat_addAPage_1(),
    m.cat_addAPage_2(),
    m.cat_addAPage_3(),
    m.cat_addAPage_4(),
    m.cat_addAPage_5(),
    m.cat_addAPage_6(),
    m.cat_addAPage_7(),
    m.cat_addAPage_8(),
    m.cat_addAPage_9(),
    m.cat_addAPage_10(),
    m.cat_addAPage_11(),
    m.cat_addAPage_12(),
    m.cat_addAPage_13(),
    m.cat_addAPage_14(),
  ],
  enoughSpaceToAddPage: [
    m.cat_enoughSpaceToAddPage_0(),
    m.cat_enoughSpaceToAddPage_1(),
    m.cat_enoughSpaceToAddPage_2(),
    m.cat_enoughSpaceToAddPage_3(),
    m.cat_enoughSpaceToAddPage_4(),
    m.cat_enoughSpaceToAddPage_5(),
    m.cat_enoughSpaceToAddPage_6(),
    m.cat_enoughSpaceToAddPage_7(),
    m.cat_enoughSpaceToAddPage_8(),
    m.cat_enoughSpaceToAddPage_9(),
    m.cat_enoughSpaceToAddPage_10(),
    m.cat_enoughSpaceToAddPage_11(),
    m.cat_enoughSpaceToAddPage_12(),
    m.cat_enoughSpaceToAddPage_13(),
    m.cat_enoughSpaceToAddPage_14(),
  ],
  taskCompleted: [
    m.cat_taskCompleted_0(),
    m.cat_taskCompleted_1(),
    m.cat_taskCompleted_2(),
    m.cat_taskCompleted_3(),
    m.cat_taskCompleted_4(),
    m.cat_taskCompleted_5(),
    m.cat_taskCompleted_6(),
    m.cat_taskCompleted_7(),
    m.cat_taskCompleted_8(),
    m.cat_taskCompleted_9(),
    m.cat_taskCompleted_10(),
    m.cat_taskCompleted_11(),
    m.cat_taskCompleted_12(),
    m.cat_taskCompleted_13(),
    m.cat_taskCompleted_14(),
  ],
  taskAdded: [
    m.cat_taskAdded_0(),
    m.cat_taskAdded_1(),
    m.cat_taskAdded_2(),
    m.cat_taskAdded_3(),
    m.cat_taskAdded_4(),
    m.cat_taskAdded_5(),
    m.cat_taskAdded_6(),
    m.cat_taskAdded_7(),
    m.cat_taskAdded_8(),
    m.cat_taskAdded_9(),
  ],
  emptyTaskDeleted: [
    m.cat_emptyTaskDeleted_0(),
    m.cat_emptyTaskDeleted_1(),
    m.cat_emptyTaskDeleted_2(),
    m.cat_emptyTaskDeleted_3(),
    m.cat_emptyTaskDeleted_4(),
    m.cat_emptyTaskDeleted_5(),
    m.cat_emptyTaskDeleted_6(),
    m.cat_emptyTaskDeleted_7(),
    m.cat_emptyTaskDeleted_8(),
    m.cat_emptyTaskDeleted_9(),
  ],
})
