export const placeholderSuggestions = [
  'uninstall valorant?',
  'clean your room?',
  'do the dishes?',
  'take out the trash?',
  'walk the dog?',
  'water the plants?',
  'do the laundry?',
  'wash the car?',
  'mow the lawn?',
  'clean the bathroom?',
  'clean the kitchen?',
  'vacuum the house?',
  'dust the furniture?',
  'clean the windows',
]
